couchpotato:
	image: linuxserver/couchpotato
	ports:
		- "5050:5050"
	volumes:
		- "/media/sf_pruebas_mediacenter/couchpotato/config:/config"
		- "/media/sf_pruebas_mediacenter/downloads:/downloads"
		- "/media/sf_pruebas_mediacenter/couchpotato/movies:/movies"
	environment:
		- PGID=0
		- PUID=0
		- TZ=London

sickrage:
	image: linuxserver/sickrage
	ports:
		- "8081:8081"
	volumes:
		- "/media/sf_pruebas_mediacenter/sickrage/config:/config"
		- "/media/sf_pruebas_mediacenter/downloads:/downloads"
		- "/media/sf_pruebas_mediacenter/sickrage/tv:/tv"
	environment:
		- PGID=0
		- PUID=0
		- TZ=London

transmission:
	image: linuxserver/transmission
	ports:
		- "9091:9091"
		- "51413:51413"
		- "51413:51413/udp"
	volumes:
		- "/media/sf_pruebas_mediacenter/transmission/config:/config"
		- "/media/sf_pruebas_mediacenter/downloads:/downloads"
		- "/media/sf_pruebas_mediacenter/transmission/watch:/watch"
    environment:
        - PGID=0
        - PUID=0
        - TZ=London

