export USER="npersia"
export SHARE_FOLDER="/media/sf_pruebas_mediacenter"
export MOUNT_FOLDER="/dev/sr0"
export NETWORK_FILE="/etc/network/interfaces"
export SERVER_IP="192.168.11.198"
export DOWNLOAD_FOLDER=$SHARE_FOLDER/downloads
export COUCHPOTATO_FOLDER=$SHARE_FOLDER/couchpotato
export COUCHPOTATO_CONFIG=$COUCHPOTATO_FOLDER/config
export COUCHPOTATO_MOVIES=$COUCHPOTATO_FOLDER/movies
export TRANSMISSION_FOLDER=$SHARE_FOLDER/transmission
export TRANSMISSION_CONFIG=$TRANSMISSION_FOLDER/config
export TRANSMISSION_WATCH=$TRANSMISSION_FOLDER/watch
export SICKRAGE_FOLDER=$SHARE_FOLDER/sickrage
export SICKRAGE_CONFIG=$SICKRAGE_FOLDER/config
export SICKRAGE_TV=$SICKRAGE_FOLDER/tv


export MINIDLNA_FOLDER=$SHARE_FOLDER/minidlna
export MINIDLNA_LOCALTIME="/etc/localtime"
